model:
  default: 255
  user:
    email_max: 255
    name_max: 50
    password_mini: 6
admin_booking:
  per_page: 10
  enum_status:
    pending: "pending"
    accept: "accept"
    rejected: "rejected"
